---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cve-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cve-consumer
  template:
    metadata:
      labels:
        app: cve-consumer
    spec:
      containers:
        - name: cve-consumer-container
          image: eashanroy7866/cve-consumer:1.0.0
          env:
          - name: db_name
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_name
          - name: db_host
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_host
          - name: db_user
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_user
          - name: db_password
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_password
          - name: db_port
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_port
          - name: kafka_host
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: kafka_host
          - name: kafka_port
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: kafka_port
          resources:
            requests:
              memory: "128Mi"
              cpu: "512m"
            limits:
              memory: "128Mi"
              cpu: "512m"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
      initContainers:
      - name: db-migration-container
        image: eashanroy7866/db-migration:1.0.0
        volumeMounts: 
        - name: flyway-config
          mountPath: /flyway/conf/flyway.conf
          subPath: flyway.conf
          readOnly: true
      volumes: 
      - name: flyway-config
        configMap:
          name: flyway-config
      imagePullSecrets:
        - name: registrypullsecret