---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cve-consumer-deployment
  namespace: {{.Values.namespace}}
  labels:
    app: cve-consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cve-consumer
  template:
    metadata:
      labels:
        app: cve-consumer
    spec:
      containers:
        - name: {{.Values.container.name}}
          image: {{.Values.container.image}}
          imagePullPolicy: Always
          env:
          - name: db_name
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_name
          - name: db_host
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_host
          - name: db_user
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_user
          - name: db_password
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_password
          - name: db_port
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_port
          - name: kafka_host
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: kafka_host
          - name: kafka_port
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: kafka_port
          - name: kafka_topic
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: kafka_topic
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 2
      initContainers:
      - name: {{.Values.initContainer.name}}
        image: {{.Values.initContainer.image}}
        imagePullPolicy: Always
        volumeMounts: 
        - name: flyway-config
          mountPath: /flyway/conf/flyway.conf
          subPath: flyway.conf
          readOnly: true
      volumes: 
      - name: flyway-config
        configMap:
          name: flyway-config
      imagePullSecrets:
        - name: registrypullsecret