---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cve-consumer-deployment
  namespace: {{.Values.namespace}}
  labels:
    app: cve-consumer
spec:
  serviceAccountName: consumer-service-account
  automountServiceAccountToken: false
  replicas: 3
  selector:
    matchLabels:
      app: cve-consumer
  template:
    metadata:
      labels:
        app: cve-consumer
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - cve-consumer
              topologyKey: topology.kubernetes.io/zone
      containers:
        - name: {{.Values.container.name}}
          image: {{.Values.container.image}}
          resources:
            requests:
              memory: "450Mi"
              cpu: "1000m"
            limits:
              memory: "600Mi"
              cpu: "1200m"
          imagePullPolicy: Always
          env:
          - name: db_name
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_name
          - name: db_host
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_host
          - name: db_user
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_user
          - name: db_password
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_password
          - name: db_port
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db_port
          - name: kafka_host
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: kafka_host
          - name: kafka_port
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: kafka_port
          - name: kafka_topic
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: kafka_topic
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 2
      initContainers:
      - name: {{.Values.initContainer.name}}
        image: {{.Values.initContainer.image}}
        imagePullPolicy: Always
        env:
        - name: FLYWAY_URL
          value: "jdbc:postgresql://postgres-0.postgres-hl.cve-consumer-namespace.svc.cluster.local:5432/cve"
        - name: FLYWAY_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db_user
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db_password
        - name: FLYWAY_SCHEMAS
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db_name
        volumeMounts: 
        - name: flyway-script-1
          mountPath: /flyway/sql/V1__init_schema.sql
          subPath: V1__init_schema.sql
          readOnly: true
        - name: flyway-script-2
          mountPath: /flyway/sql/V2__modify_tables.sql
          subPath: V2__modify_tables.sql
          readOnly: true
        - name: flyway-script-3
          mountPath: /flyway/sql/V3__create_views.sql
          subPath: V3__create_views.sql
          readOnly: true
        command: ["flyway", "migrate"]
      volumes: 
      - name: flyway-script-1
        configMap:
          name: flyway-script-1
      - name: flyway-script-2
        configMap:
          name: flyway-script-2
      - name: flyway-script-3
        configMap:
          name: flyway-script-3
      imagePullSecrets:
        - name: registrypullsecret