apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cve-consumer-pdb
  namespace: {{.Values.namespace}}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: cve-consumer
