apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-storage-class
  namespace: {{.Values.namespace}}
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: gp2
  iopsPerGB: "50"
  encrypted: "true"
allowedTopologies:
- matchLabelExpressions:
  - key: topology.ebs.csi.aws.com/zone
    values:
    - us-east-1b
    - us-east-1c
    - us-east-1d